---
- name: Configure base system
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    target_user: "{{ ansible_user | default('support') }}"
    
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Ensure log directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /var/log/ansible
        - /var/log/installer
        
  roles:
    - baseline
    - tooling
    - monitoring
    
  post_tasks:
    - name: Log base configuration completion
      lineinfile:
        path: /var/log/ansible/base.log
        line: "{{ ansible_date_time.iso8601 }}: Base configuration completed successfully"
        create: yes
        
    - name: Create system info file
      template:
        src: system-info.j2
        dest: /etc/system-info
        mode: '0644'
      vars:
        build_date: "{{ ansible_date_time.iso8601 }}"
        ansible_version: "{{ ansible_version.full }}"
